// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: game/common/transform.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_game_common_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_game_common_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_game_common_transform_proto_rawDescGZIP(), []int{0}
}

func (x *Transform) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Transform) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Transform) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Transform) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

var File_game_common_transform_proto protoreflect.FileDescriptor

const file_game_common_transform_proto_rawDesc = "" +
	"\n" +
	"\x1bgame/common/transform.proto\x12\vgame.common\"G\n" +
	"\tTransform\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yawB(Z&example/game-server/game/common;commonb\x06proto3"

var (
	file_game_common_transform_proto_rawDescOnce sync.Once
	file_game_common_transform_proto_rawDescData []byte
)

func file_game_common_transform_proto_rawDescGZIP() []byte {
	file_game_common_transform_proto_rawDescOnce.Do(func() {
		file_game_common_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_common_transform_proto_rawDesc), len(file_game_common_transform_proto_rawDesc)))
	})
	return file_game_common_transform_proto_rawDescData
}

var file_game_common_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_common_transform_proto_goTypes = []any{
	(*Transform)(nil), // 0: game.common.Transform
}
var file_game_common_transform_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_common_transform_proto_init() }
func file_game_common_transform_proto_init() {
	if File_game_common_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_common_transform_proto_rawDesc), len(file_game_common_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_common_transform_proto_goTypes,
		DependencyIndexes: file_game_common_transform_proto_depIdxs,
		MessageInfos:      file_game_common_transform_proto_msgTypes,
	}.Build()
	File_game_common_transform_proto = out.File
	file_game_common_transform_proto_goTypes = nil
	file_game_common_transform_proto_depIdxs = nil
}
