// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: game/lobby/lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "openworld/game-server/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_game_lobby_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_lobby_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_game_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReply) Reset() {
	*x = JoinReply{}
	mi := &file_game_lobby_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReply) ProtoMessage() {}

func (x *JoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_lobby_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReply.ProtoReflect.Descriptor instead.
func (*JoinReply) Descriptor() ([]byte, []int) {
	return file_game_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *JoinReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_game_lobby_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_lobby_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_game_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_game_lobby_lobby_proto protoreflect.FileDescriptor

const file_game_lobby_lobby_proto_rawDesc = "" +
	"\n" +
	"\x16game/lobby/lobby.proto\x12\n" +
	"game.lobby\x1a\x12common/empty.proto\")\n" +
	"\vJoinRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\"%\n" +
	"\tJoinReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\fLeaveRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId2x\n" +
	"\fLobbyService\x126\n" +
	"\x04Join\x12\x17.game.lobby.JoinRequest\x1a\x15.game.lobby.JoinReply\x120\n" +
	"\x05Leave\x12\x18.game.lobby.LeaveRequest\x1a\r.common.EmptyB&Z$example/game-server/game/lobby;lobbyb\x06proto3"

var (
	file_game_lobby_lobby_proto_rawDescOnce sync.Once
	file_game_lobby_lobby_proto_rawDescData []byte
)

func file_game_lobby_lobby_proto_rawDescGZIP() []byte {
	file_game_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_game_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_lobby_lobby_proto_rawDesc), len(file_game_lobby_lobby_proto_rawDesc)))
	})
	return file_game_lobby_lobby_proto_rawDescData
}

var file_game_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_lobby_lobby_proto_goTypes = []any{
	(*JoinRequest)(nil),  // 0: game.lobby.JoinRequest
	(*JoinReply)(nil),    // 1: game.lobby.JoinReply
	(*LeaveRequest)(nil), // 2: game.lobby.LeaveRequest
	(*common.Empty)(nil), // 3: common.Empty
}
var file_game_lobby_lobby_proto_depIdxs = []int32{
	0, // 0: game.lobby.LobbyService.Join:input_type -> game.lobby.JoinRequest
	2, // 1: game.lobby.LobbyService.Leave:input_type -> game.lobby.LeaveRequest
	1, // 2: game.lobby.LobbyService.Join:output_type -> game.lobby.JoinReply
	3, // 3: game.lobby.LobbyService.Leave:output_type -> common.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_lobby_lobby_proto_init() }
func file_game_lobby_lobby_proto_init() {
	if File_game_lobby_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_lobby_lobby_proto_rawDesc), len(file_game_lobby_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_game_lobby_lobby_proto_depIdxs,
		MessageInfos:      file_game_lobby_lobby_proto_msgTypes,
	}.Build()
	File_game_lobby_lobby_proto = out.File
	file_game_lobby_lobby_proto_goTypes = nil
	file_game_lobby_lobby_proto_depIdxs = nil
}
