// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: game/realtime/movement.proto

package realtime

import (
	common "example/game-server/game/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Transform     *common.Transform      `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	mi := &file_game_realtime_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_game_realtime_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_game_realtime_movement_proto_rawDescGZIP(), []int{0}
}

func (x *ClientState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ClientState) GetTransform() *common.Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type WorldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*common.PlayerState  `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_game_realtime_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_game_realtime_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_game_realtime_movement_proto_rawDescGZIP(), []int{1}
}

func (x *WorldState) GetPlayers() []*common.PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_game_realtime_movement_proto protoreflect.FileDescriptor

const file_game_realtime_movement_proto_rawDesc = "" +
	"\n" +
	"\x1cgame/realtime/movement.proto\x12\rgame.realtime\x1a\x1bgame/common/transform.proto\x1a\x18game/common/player.proto\"_\n" +
	"\vClientState\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x124\n" +
	"\ttransform\x18\x02 \x01(\v2\x16.game.common.TransformR\ttransform\"@\n" +
	"\n" +
	"WorldState\x122\n" +
	"\aplayers\x18\x01 \x03(\v2\x18.game.common.PlayerStateR\aplayers2W\n" +
	"\x0fRealtimeService\x12D\n" +
	"\aConnect\x12\x1a.game.realtime.ClientState\x1a\x19.game.realtime.WorldState(\x010\x01B,Z*example/game-server/game/realtime;realtimeb\x06proto3"

var (
	file_game_realtime_movement_proto_rawDescOnce sync.Once
	file_game_realtime_movement_proto_rawDescData []byte
)

func file_game_realtime_movement_proto_rawDescGZIP() []byte {
	file_game_realtime_movement_proto_rawDescOnce.Do(func() {
		file_game_realtime_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_realtime_movement_proto_rawDesc), len(file_game_realtime_movement_proto_rawDesc)))
	})
	return file_game_realtime_movement_proto_rawDescData
}

var file_game_realtime_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_realtime_movement_proto_goTypes = []any{
	(*ClientState)(nil),        // 0: game.realtime.ClientState
	(*WorldState)(nil),         // 1: game.realtime.WorldState
	(*common.Transform)(nil),   // 2: game.common.Transform
	(*common.PlayerState)(nil), // 3: game.common.PlayerState
}
var file_game_realtime_movement_proto_depIdxs = []int32{
	2, // 0: game.realtime.ClientState.transform:type_name -> game.common.Transform
	3, // 1: game.realtime.WorldState.players:type_name -> game.common.PlayerState
	0, // 2: game.realtime.RealtimeService.Connect:input_type -> game.realtime.ClientState
	1, // 3: game.realtime.RealtimeService.Connect:output_type -> game.realtime.WorldState
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_realtime_movement_proto_init() }
func file_game_realtime_movement_proto_init() {
	if File_game_realtime_movement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_realtime_movement_proto_rawDesc), len(file_game_realtime_movement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_realtime_movement_proto_goTypes,
		DependencyIndexes: file_game_realtime_movement_proto_depIdxs,
		MessageInfos:      file_game_realtime_movement_proto_msgTypes,
	}.Build()
	File_game_realtime_movement_proto = out.File
	file_game_realtime_movement_proto_goTypes = nil
	file_game_realtime_movement_proto_depIdxs = nil
}
