// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: game/common/player.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Transform     *Transform             `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_common_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_common_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_common_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetTransform() *Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

var File_game_common_player_proto protoreflect.FileDescriptor

const file_game_common_player_proto_rawDesc = "" +
	"\n" +
	"\x18game/common/player.proto\x12\vgame.common\x1a\x1bgame/common/transform.proto\"_\n" +
	"\vPlayerState\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x124\n" +
	"\ttransform\x18\x02 \x01(\v2\x16.game.common.TransformR\ttransformB(Z&example/game-server/game/common;commonb\x06proto3"

var (
	file_game_common_player_proto_rawDescOnce sync.Once
	file_game_common_player_proto_rawDescData []byte
)

func file_game_common_player_proto_rawDescGZIP() []byte {
	file_game_common_player_proto_rawDescOnce.Do(func() {
		file_game_common_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_common_player_proto_rawDesc), len(file_game_common_player_proto_rawDesc)))
	})
	return file_game_common_player_proto_rawDescData
}

var file_game_common_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_common_player_proto_goTypes = []any{
	(*PlayerState)(nil), // 0: game.common.PlayerState
	(*Transform)(nil),   // 1: game.common.Transform
}
var file_game_common_player_proto_depIdxs = []int32{
	1, // 0: game.common.PlayerState.transform:type_name -> game.common.Transform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_common_player_proto_init() }
func file_game_common_player_proto_init() {
	if File_game_common_player_proto != nil {
		return
	}
	file_game_common_transform_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_common_player_proto_rawDesc), len(file_game_common_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_common_player_proto_goTypes,
		DependencyIndexes: file_game_common_player_proto_depIdxs,
		MessageInfos:      file_game_common_player_proto_msgTypes,
	}.Build()
	File_game_common_player_proto = out.File
	file_game_common_player_proto_goTypes = nil
	file_game_common_player_proto_depIdxs = nil
}
